# Translations template for heat.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the heat project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: heat 6.0.0.0b2.dev223\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-01-18 06:34+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: heat/api/aws/ec2token.py:188
msgid "Ec2Token authorization failed, no auth_uri specified in config file"
msgstr ""

#: heat/api/aws/utils.py:101
#, python-format
msgid "Request does not contain %s parameter!"
msgstr ""

#: heat/api/cloudwatch/watch.py:253
msgid "Request does not contain required MetricData"
msgstr ""

#: heat/common/context.py:218
msgid "Keystone v3 API connection failed, no password trust or auth_token!"
msgstr ""

#: heat/common/exception.py:57
msgid "Exception in string format operation"
msgstr ""

#: heat/common/exception.py:59
#, python-format
msgid "%(name)s: %(value)s"
msgstr ""

#: heat/common/heat_keystoneclient.py:130
#: heat/common/heat_keystoneclient.py:211
msgid "Domain admin client authentication failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:156
#: heat/common/heat_keystoneclient.py:358
msgid "Keystone client authentication failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:162
msgid "trust token re-scoping failed!"
msgstr ""

#: heat/common/heat_keystoneclient.py:166
msgid "Trust impersonation failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:281
#: heat/common/heat_keystoneclient.py:343
#, python-format
msgid "Failed to add user %(user)s to role %(role)s, check role exists!"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:45
msgid "failed to get lifecycle plug point classes"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:52
#, python-format
msgid "failed to instantiate stack lifecycle class %s"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:57
msgid "failed to sort lifecycle plug point classes"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:111
#, python-format
msgid "%(opname)s %(ci)s failed for %(a)s on %(sid)s"
msgstr ""

#: heat/common/plugin_loader.py:100
#, python-format
msgid "Failed to import module %s"
msgstr ""

#: heat/common/wsgi.py:287
msgid "SIGTERM received"
msgstr ""

#: heat/common/wsgi.py:295
msgid "SIGHUP received"
msgstr ""

#: heat/common/wsgi.py:432
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: heat/common/wsgi.py:842
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: heat/common/wsgi.py:864
#, python-format
msgid "Returning %(code)s to user: %(explanation)s"
msgstr ""

#: heat/common/wsgi.py:938
#, python-format
msgid "Unexpected error occurred serving API: %s"
msgstr ""

#: heat/engine/api.py:43
msgid "Timeout conversion failed"
msgstr ""

#: heat/engine/api.py:444
msgid "Unexpected number of keys in watch_data.data!"
msgstr ""

#: heat/engine/environment.py:725
#, python-format
msgid "Failed to read %s"
msgstr ""

#: heat/engine/environment.py:737
#, python-format
msgid "Failed to parse %(file_path)s"
msgstr ""

#: heat/engine/environment.py:741
#, python-format
msgid "Failed to read %(file_path)s"
msgstr ""

#: heat/engine/plugin_manager.py:95
#, python-format
msgid "Failed to load %(mapping_name)s from %(module)s"
msgstr ""

#: heat/engine/plugin_manager.py:102
#, python-format
msgid "Invalid type for %(mapping_name)s from %(module)s"
msgstr ""

#: heat/engine/resource.py:643
msgid "Error marking resource as failed"
msgstr ""

#: heat/engine/resource.py:1346 heat/engine/resource.py:1393
#: heat/engine/resource.py:1421
#, python-format
msgid "DB error %s"
msgstr ""

#: heat/engine/resource.py:1426
#, python-format
msgid ""
"Error acquiring lock for resource id:%(resource_id)s with "
"atomic_key:%(atomic_key)s, engine_id:%(rs_engine_id)s/%(engine_id)s"
msgstr ""

#: heat/engine/resource.py:1698
#, python-format
msgid "signal %(name)s : %(msg)s"
msgstr ""

#: heat/engine/service.py:129
msgid "Unhandled error in asynchronous task"
msgstr ""

#: heat/engine/service.py:389
#, python-format
msgid "Failed to stop engine service, %s"
msgstr ""

#: heat/engine/service.py:806
msgid ""
"PATCH update to FAILED stack only possible if convergence enabled or "
"previous template stored"
msgstr ""

#: heat/engine/service.py:1289 heat/engine/service.py:1335
#, python-format
msgid "Error loading resource type %s from global environment."
msgstr ""

#: heat/engine/service.py:1717
msgid "Filtering by namespace/metric not yet supported"
msgstr ""

#: heat/engine/service.py:1865
#, python-format
msgid "Service %(service_id)s update failed: %(error)s"
msgstr ""

#: heat/engine/service.py:1942
#, python-format
msgid "Error while resetting stack: %s"
msgstr ""

#: heat/engine/service_stack_watch.py:75
#, python-format
msgid "Unable to retrieve stack %s for periodic task"
msgstr ""

#: heat/engine/stack.py:85
#, python-format
msgid "Unexpected exception in %(func)s: %(msg)s"
msgstr ""

#: heat/engine/stack.py:710
#, python-format
msgid "Exception: %s"
msgstr ""

#: heat/engine/stack.py:1268
#, python-format
msgid "Unexpected action %s passed to update!"
msgstr ""

#: heat/engine/stack.py:1550
#, python-format
msgid "Unexpected action %s passed to delete!"
msgstr ""

#: heat/engine/stack.py:1753
#, python-format
msgid "Resource %(name)s delete failed: %(ex)s"
msgstr ""

#: heat/engine/stack.py:1762
#, python-format
msgid "Resource %(name)s create failed: %(ex)s"
msgstr ""

#: heat/engine/worker.py:90
#, python-format
msgid "%(topic)s is failed to stop, %(exc)s"
msgstr ""

#: heat/engine/clients/os/zaqar.py:42
msgid "Zaqar connection failed, no auth_token!"
msgstr ""

#: heat/engine/resources/stack_resource.py:434
msgid "update_stack"
msgstr ""

#: heat/engine/resources/wait_condition.py:73
#, python-format
msgid "Metadata failed validation for %s"
msgstr ""

#: heat/engine/resources/aws/autoscaling/autoscaling_group.py:308
msgid "Failed sending error notification"
msgstr ""

#: heat/engine/resources/aws/ec2/eip.py:116
msgid ""
"No default floating IP pool configured. Set 'default_floating_pool' in "
"nova.conf."
msgstr ""

#: heat/engine/resources/aws/ec2/eip.py:333
#: heat/engine/resources/aws/ec2/eip.py:356
msgid "Port not specified."
msgstr ""

#: heat/engine/resources/openstack/heat/remote_stack.py:156
#, python-format
msgid "exception: %s"
msgstr ""

#: heat/engine/resources/openstack/nova/floatingip.py:84
msgid ""
"Could not allocate floating IP. Probably there is no default floating IP "
"pool is configured."
msgstr ""

#: heat/engine/resources/openstack/nova/server.py:1131
msgid "Error while updating software config transport"
msgstr ""

#: heat/tests/convergence/framework/scenario.py:25
#, python-format
msgid "Scenario directory \"%s\" not found"
msgstr ""

