# Translations template for heat.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the heat project.
#
# Translators:
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Heat\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-04-02 06:02+0000\n"
"PO-Revision-Date: 2015-04-02 01:48+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/heat/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: heat/api/aws/ec2token.py:189
msgid "Ec2Token authorization failed, no auth_uri specified in config file"
msgstr ""
"Échec de l’autorisation Ec2Token, pas auth_uri spécifié dans le fichier de "
"configuration"

#: heat/api/aws/utils.py:99
#, python-format
msgid "Request does not contain %s parameter!"
msgstr "La requete ne doit pas contenir le paramètre %s!"

#: heat/api/cloudwatch/watch.py:253
msgid "Request does not contain required MetricData"
msgstr "La requête ne doit pas contenir comme pré-requis MetricData"

#: heat/common/context.py:200
msgid "Keystone v3 API connection failed, no password trust or auth_token!"
msgstr ""
"Échec de la connexion Keystone v3 API, pas de mot de passe de confiance ou "
"auth_token!"

#: heat/common/exception.py:114
msgid "Exception in string format operation"
msgstr "Exception dans le formatage de la chaîne"

#: heat/common/heat_keystoneclient.py:125
msgid "Admin client authentication failed"
msgstr "Echec d'authentification Admin client"

#: heat/common/heat_keystoneclient.py:146
msgid "Domain admin client authentication failed"
msgstr "Echec d'authentification Domain admin client"

#: heat/common/heat_keystoneclient.py:160
msgid "Keystone client authentication failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:166
msgid "trust token re-scoping failed!"
msgstr ""

#: heat/common/heat_keystoneclient.py:170
msgid "Trust impersonation failed"
msgstr ""

#: heat/common/heat_keystoneclient.py:300
#: heat/common/heat_keystoneclient.py:372
#, python-format
msgid "Failed to add user %(user)s to role %(role)s, check role exists!"
msgstr ""
"Échec d'ajout de l'utilisateur %(user)s pour le rôle %(role)s, vérifier si "
"le role existe!"

#: heat/common/lifecycle_plugin_utils.py:46
msgid "failed to get lifecycle plug point classes"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:53
#, python-format
msgid "failed to instantiate stack lifecycle class %s"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:58
msgid "failed to sort lifecycle plug point classes"
msgstr ""

#: heat/common/lifecycle_plugin_utils.py:111
#, python-format
msgid "%(opname) %(ci)s failed for %(a)s on %(sid)s"
msgstr "%(opname) %(ci)s échec pour  %(a)s sur %(sid)s"

#: heat/common/plugin_loader.py:100
#, python-format
msgid "Failed to import module %s"
msgstr "Echec lors de l'import du module %s"

#: heat/common/wsgi.py:256
msgid "SIGTERM received"
msgstr "SIGTERM reçu"

#: heat/common/wsgi.py:265
msgid "SIGHUP received"
msgstr "SIGHUP reçu"

#: heat/common/wsgi.py:295
#, python-format
msgid "Removing dead child %s"
msgstr "Retrait de l'enfant arrêté %s"

#: heat/common/wsgi.py:652
#, python-format
msgid "Exception handling resource: %s"
msgstr "Exception lors du traitement de la ressource : %s"

#: heat/common/wsgi.py:674
#, python-format
msgid "Returning %(code)s to user: %(explanation)s"
msgstr "Renvoie %(code)s à l'utilisateur : %(explanation)s"

#: heat/common/wsgi.py:748
#, python-format
msgid "Unexpected error occurred serving API: %s"
msgstr ""

#: heat/engine/api.py:41
msgid "Timeout conversion failed"
msgstr ""

#: heat/engine/api.py:299
msgid "Unexpected number of keys in watch_data.data!"
msgstr ""

#: heat/engine/environment.py:580
#, python-format
msgid "Failed to read %s"
msgstr "Echec de lecture %s"

#: heat/engine/environment.py:592
#, python-format
msgid "Failed to parse %(file_path)s"
msgstr "Echec d'analyse  %(file_path)s"

#: heat/engine/environment.py:596
#, python-format
msgid "Failed to read %(file_path)s"
msgstr "Echec de lecture %(file_path)s"

#: heat/engine/plugin_manager.py:97
#, python-format
msgid "Failed to load %(mapping_name)s from %(module)s"
msgstr "Echec de chargement %(mapping_name)s depuis %(module)s"

#: heat/engine/plugin_manager.py:104
#, python-format
msgid "Invalid type for %(mapping_name)s from %(module)s"
msgstr "Type invalide pour  %(mapping_name)s depuis %(module)s"

#: heat/engine/resource.py:505
msgid "Error marking resource as failed"
msgstr ""

#: heat/engine/resource.py:973 heat/engine/resource.py:1014
#, python-format
msgid "DB error %s"
msgstr "Erreur base de donné %s"

#: heat/engine/resource.py:1157
#, python-format
msgid "signal %(name)s : %(msg)s"
msgstr "signal %(name)s : %(msg)s"

#: heat/engine/service.py:366
#, python-format
msgid "Failed to stop engine service, %s"
msgstr ""

#: heat/engine/service.py:1400
msgid "Filtering by namespace/metric not yet supported"
msgstr ""

#: heat/engine/service_stack_watch.py:74
#, python-format
msgid "Unable to retrieve stack %s for periodic task"
msgstr "Impossible de récupérer la stack %s pour la tache périodique"

#: heat/engine/stack.py:615
#, python-format
msgid "Exception: %s"
msgstr ""

#: heat/engine/stack.py:878
#, python-format
msgid "Unexpected action %s passed to update!"
msgstr "Action inattendu %s à mettre à jour!"

#: heat/engine/stack.py:1111
#, python-format
msgid "Unexpected action %s passed to delete!"
msgstr "Action inattendu %s à supprimer!"

#: heat/engine/stack.py:1299
#, python-format
msgid "Resource %(name)s delete failed: %(ex)s"
msgstr "Ressource %(name)s échec de suppression: %(ex)s"

#: heat/engine/stack.py:1308
#, python-format
msgid "Resource %(name)s create failed: %(ex)s"
msgstr ""

#: heat/engine/worker.py:76
#, python-format
msgid "WorkerService is failed to stop, %s"
msgstr ""

#: heat/engine/clients/__init__.py:143
#, python-format
msgid "Invalid cloud_backend setting in heat.conf detected  - %s"
msgstr ""

#: heat/engine/resources/wait_condition.py:72
#, python-format
msgid "Metadata failed validation for %s"
msgstr "Echec de validation de metadata pour %s"

#: heat/engine/resources/aws/autoscaling/autoscaling_group.py:336
msgid "Failed sending error notification"
msgstr ""

#: heat/engine/resources/aws/ec2/eip.py:113
msgid ""
"No default floating IP pool configured. Set 'default_floating_pool' in nova."
"conf."
msgstr ""

#: heat/engine/resources/aws/ec2/eip.py:327
#: heat/engine/resources/aws/ec2/eip.py:350
msgid "Port not specified."
msgstr "Port non spécifié"

#: heat/engine/resources/openstack/heat/remote_stack.py:148
#, python-format
msgid "exception: %s"
msgstr ""

#: heat/engine/resources/openstack/nova/nova_floatingip.py:78
msgid ""
"Could not allocate floating IP. Probably there is no default floating IP "
"pool is configured."
msgstr ""

#: heat/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "dans l'appel en boucle de durée fixe"

#: heat/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "dans l'appel en boucle dynamique"

#: heat/openstack/common/policy.py:563 heat/openstack/common/policy.py:843
#, python-format
msgid "Failed to understand rule %s"
msgstr "Règle %s incompréhensible"

#: heat/openstack/common/policy.py:573
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Aucun gestionnaire pour les correspondances de type %s"

#: heat/openstack/common/service.py:264
msgid "Unhandled exception"
msgstr "Exception non gérée"
